### PR TITLE
Add user model, add login links/view

### PR DESCRIPTION
**Pull request by ty10r**
Incomplete atm, waiting on server side changes.
TODO:
- [x] Implement save_step and save_connection
- [x] Handle login errors
- [x] Integrate with other pages making requests specific to a user

### CODE REVIEW

**Comment by ty10r** [comment]
I'm not entirely sure about how to go about communicating errors between the api and these pages.

**Comment by ty10r** [comment]
cc @dthompson

**Comment by ondrae** [comment]
Once we figure out the password matching [bug](https://github.com/codeforamerica/howtocity-api/pull/30]) then lets finished the code for signing in to BizFriendly.

```
function _signedIn(response){
    console.log(response);
  }
```

**Comment by ty10r** [comment]
does the sign-in code from user.js not work? I know the names should be changed from _login to _signin but looking at the code it seems like the same functionality is being moved out of the user model

**Comment by ondrae** [comment]
It does, I copy and pasted it over. I just split things up for now to work my through it all. Most likely will combine it back to the way you had it, once we get each piece working. I'll do another round on it tomorrow afternoon.

**Comment by ty10r** [comment]
@ondrae This should be good to go for merging with bootstrap3 and testing

**Comment by ondrae** [comment]
All included. Thanks @ty10r

**Pull request closed without merging**
