### PR TITLE
Remove some time precision to fix Date.parse issue in IE9

### LINKED ISSUE #172: Latest Activity different in IE9
#### Description

When viewed in Internet Explorer 9, the latest activity feed is static. On any other browser it updates based on date.
#### IE9

screen shot 2014-01-25 at 9 16 33 am
#### Chrome

screen shot 2014-01-25 at 9 16 52 am
#### Files

js/connect.js _getLatestActivity(response)
Check out the sort function with the date filter.

### PR DESCRIPTION
**Pull request by kborchers**
Closes gh-172

### CODE REVIEW

**Comment by ondrae** [comment]
Fantastic. I'm on the road til next week and will check this out then. Thanks!

**Comment by ondrae** [comment]
Thanks @kborchers, it works.

How did you know that you needed to trim the decimals for time comparison to work in ie9?

How did you find this issue anyways?

**Comment by kborchers** [comment]
I traced the issue to Date.parse returning NaN so read the Date docs for IE and saw they expected that specific precision.

As for how I found the issue, I was just looking at the Code for America site and that issue happened to pop up as needing help so I jumped on it. After taking over as ED of the jQuery Foundation I don't get to write code much anymore so I've been looking for little places here and there to throw my JS skills at projects that need help.

**Comment by ondrae** [comment]
Hi @kborchers thanks again for the help.

I'm writing a blog post to announce the [Civic Tech Issue Finder](http://www.codeforamerica.org/geeks/civicissues). Can I use your quote above in the post?

**Comment by kborchers** [comment]
Sure, no problem. A link once it's up would be great.

**Comment by ondrae** [comment]
Its done http://www.codeforamerica.org/blog/2014/10/30/the-civic-tech-issue-finder/ 
Let me know if you have any edits. Thanks again.

We just hit 2500 clicks on different civic tech issues. Its working!

**Pull request merged**
