### PR TITLE
About page margins and optional style rule additions & markup formatting

### PR DESCRIPTION
**Pull request by nickjellings**
I've provided two commits as part of this pull request. One was for resolving the margins. The second was for providing some additional suggestions regarding styling of the About page to make it more closely reflect the styles from the Teaching Guide page.

### CODE REVIEW

**Comment by ondrae** [comment]
Great work! Won't be as embarrassed to show what the site is about to libraries and nonprofits now! Thanks much @nickjellings 

How did you find this project and issue?

**Comment by nickjellings** [comment]
I was referred to CodeForAmerican from a colleague after expressing
interest in continuing to develop my coding skills. Found the "Help Wanted"
area as part of the Civic Tech Issue Finder and thought I could lend a hand.

On Mon, Sep 8, 2014 at 8:12 PM, Andrew Hyder notifications@github.com
wrote:

> Great work! Won't be as embarrassed to show what the site is about to
> libraries and nonprofits now! Thanks much @nickjellings
> https://github.com/nickjellings
> 
> How did you find this project and issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/bizfriendly-web/pull/179#issuecomment-54910790
> .

## 

Nick Jellings // 563-379-4746 (cell) // nickjellings@gmail.com

**Comment by ondrae** [comment]
@nickjellings is it okay with you if I use this as a quote in my blog post about the Civic Tech Issue finder?

**Comment by nickjellings** [comment]
Go for it!

**Comment by arielkennan** [comment]
Just wanted to chime in and say THANK YOU @nickjellings!!! I'm Andrew's partner in crime on BizFriend.ly and the designer. Thanks so much for your help on these improvements and bringing style to all of our pages. Truly appreciated!!=

**Comment by nickjellings** [comment]
My pleasure @arielkennan! Although, I'm afraid I may be at the end of my helpful stint. The remaining "help wanted" issues are relating to IE9, and I am unable to get that on my operating system. :(

(cc: @ondrae )

**Pull request merged**
