### PR TITLE
Refactors JavaScript to be modularized

### PR DESCRIPTION
**Pull request by anselmbradford**
Refactors JavaScript into an "instructions" module to avoid polluting
the global scope with properties. Also moves nested functions to the
module scope and establishes public/private scope of module properties
and methods.

### CODE REVIEW

**Comment by ondrae** [comment]
Cool! Thanks Ans! I obviously have a lot to learn, this code appears to be illuminating. I'll check out in more depth when I get to the office.

**Comment by ondrae** [comment]
This is great, thanks again. One question though, what does (instructions || {}) do?

**Comment by anselmbradford** [comment]
This follows a asynchronous module pattern... so you can extend this in other files... for instance, maybe you have `othersteps.js` somewhere else. You can use this same pattern to append methods to `instructions.js`. `othersteps.js` might look like:

```
var instructions = (function (othersteps) {
   function stepUp(){
      // do yo stuff
   }

   // set public methods
   othersteps.stepUp = stepUp;
   return othersteps;
}(instructions || {}));
```

So what happens is `(instructions || {}));` gets handed to the first line `var othersteps = (function (othersteps) {` and sets the `othersteps` variable equal to `instructions` within the scope of this module. If `instructions` is already defined (as it is in `instructions.js`) that gets passed in and appended with a public `stepUp` method. If on the other hand it is not defined, an empty object gets passed in `{}`, which initializes the `instructions` variable in the first place. This way either `instructions.js` or `othersteps.js` could be loaded first, the order doesn't matter, and you still end up with a variable at `window.instructions` that has the public methods of both scripts.

**Comment by anselmbradford** [comment]
oops, first line is `var instructions = (function (othersteps) {` as shown in the code block, not `var othersteps = (function (othersteps) {`

**Pull request merged**
